version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: volunteerhub_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: volunteerhub
      MYSQL_USER: vh_user
      MYSQL_PASSWORD: vh_pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
