package com.volunteerhub.backend.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.Setter;

/**
 * Data Transfer Object for registering a browser push subscription.
 * This DTO captures the endpoint and cryptographic keys provided by the 
 * browser's PushManager, allowing the backend to send encrypted push 
 * notifications to a specific user device.
 */
@Getter
@Setter
public class PushSubscriptionRequest {

    /**
     * The unique URL provided by the Push Service (e.g., Google FCM, Mozilla Autopush).
     * This endpoint is used by the backend to trigger the delivery of a push message.
     */
    @NotBlank
    private String endpoint;

    /**
     * A JSON string containing the public key (p256dh) and the authentication 
     * secret (auth) generated by the browser. 
     * These keys are required to encrypt the notification payload so that 
     * only the user's browser can decrypt it.
     */
    private String keysJson;
}