package com.volunteerhub.backend.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Data Transfer Object for completing the password reset process.
 * This DTO carries the verification token sent via email and the user's 
 * newly chosen password to finalize the account recovery.
 */
public class ResetPasswordRequest {

    /**
     * The unique, time-sensitive security token generated by the system.
     * This token validates that the user has access to the registered email 
     * account and is authorized to change the password.
     */
    @NotBlank
    private String token;

    /**
     * The new password the user wishes to set for their account.
     * Enforces a minimum length of 8 characters to ensure a higher 
     * standard of security for recovered accounts.
     */
    @NotBlank
    @Size(min = 8, message = "Password must be at least 8 characters")
    private String newPassword;

    /**
     * Gets the recovery token.
     * @return the security token string.
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the recovery token.
     * @param token the token string usually retrieved from a URL parameter.
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * Gets the new password.
     * @return the plain-text new password.
     */
    public String getNewPassword() {
        return newPassword;
    }

    /**
     * Sets the new password.
     * @param newPassword the new password string provided by the user.
     */
    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }
}