package com.volunteerhub.backend.config;

import io.swagger.v3.oas.models.ExternalDocumentation;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import io.swagger.v3.oas.models.OpenAPI;

/**
 * Configuration for OpenAPI (Swagger) documentation.
 * This class defines the metadata and grouping rules for the API documentation 
 * generated by SpringDoc, accessible via the Swagger UI.
 */
@Configuration
public class OpenApiConfig {

    /**
     * Defines the core OpenAPI metadata for the VolunteerHub project.
     * Includes the API title, detailed description, version, and developer contact information.
     * * @return An {@link OpenAPI} object containing global API information.
     */
    @Bean
    public OpenAPI volunteerHubOpenAPI() {
        return new OpenAPI()
                .info(new Info().title("VolunteerHub API")
                        .description("VolunteerHub — Backend API documentation")
                        .version("v1.0")
                        .contact(new Contact().name("VolunteerHub Team").email("dev@volunteerhub.test")));
    }

    /**
     * Configures a grouped API specifically for public-facing endpoints.
     * It scans the controller package to automatically detect and document all available REST endpoints.
     * * @return A {@link GroupedOpenApi} configured to scan the controller package.
     */
    @Bean
    public GroupedOpenApi publicApi() {
        return GroupedOpenApi.builder()
                .group("volunteerhub-public")
                .packagesToScan("com.volunteerhub.backend.controller")
                .build();
    }
}