spring:
  datasource:
    url: jdbc:mysql://localhost:3306/volunteerhub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: vh_user
    password: vh_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # Flyway creates schema; don't let Hibernate alter
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    # baseline-on-migrate: false   # default false; change only if you want baseline behavior

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
