spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/volunteerhub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${SPRING_DATASOURCE_USERNAME:vh_user}
    password: ${SPRING_DATASOURCE_PASSWORD:vh_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

webpush:
  vapid:
    public-key: BG0M7NIgM1tXh8m6iEbr6pYdYLlGsrMUYcGp2HwB8GpRq0RjZpxum1nzsPFQOIOMbUFsVE-wkW1bBc78U_9lh8M
    private-key: tZv0VqD-lwzXk2nMKw_9x8J_AFwx8cteZC2PHb6xS4Y
    subject: mailto:admin@volunteerhub.test

jwt:
  secret: ${JWT_SECRET:change_this_to_a_very_long_random_secret_key_for_dev_only}
  expirationMs: ${JWT_EXP_MS:3600000}

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
