spring.application.name=backend
# Cấu hình JWT (Bắt buộc phải có để Login)
# Khóa bí mật phải đủ dài (ít nhất 32 ký tự)
volunteerhub.app.jwtSecret=VolunteerHubSecretKeyGenZDeveloper2025VietNamVodich
volunteerhub.app.jwtExpirationMs=86400000